sequenceDiagram
    participant Client
    participant #58;AppModule
    participant #58;AuthService
    participant #58;BookingController
    participant #58;BookingService
    participant #58;DB

    Client ->>+ #58;AppModule : GET /booking 

    #58;AppModule ->>+ #58;AuthService : Validate token
    #58;AuthService -->>- #58;AppModule : Response
    
    #58;AppModule->>+#58;BookingController: Retrieve bookings
    #58;BookingController->>+#58;BookingService: Retrieve bookings
    #58;BookingService->>+#58;DB: Retrieve bookings
    #58;DB-->>-#58;BookingService: Bookings detail
    #58;BookingService-->>-#58;BookingController: Bookings detail
    #58;BookingController-->>-#58;AppModule: Bookings detail
    
    #58;AppModule-->>-Client: Bookings detail