sequenceDiagram
    participant Client
    participant #58;AppModule
    participant #58;AuthService
    participant #58;BookingController
    participant #58;BookingService
    participant #58;DB

    Client ->>+ #58;AppModule : PATCH /booking/:id 

    #58;AppModule ->>+ #58;AuthService : Validate token
    #58;AuthService -->>- #58;AppModule : Response

    #58;AppModule->>+#58;BookingController: Edit booking
    #58;BookingController->>+#58;BookingService: Edit booking
    #58;BookingService->>+#58;DB: Edit booking
    #58;DB-->>-#58;BookingService: Updated booking detail
    #58;BookingService-->>-#58;BookingController: Updated booking detail
    #58;BookingController-->>-#58;AppModule: Updated booking detail
    
    #58;AppModule-->>-Client: Updated booking detail